### ISSUE TITLE
Can't access external articles through RSS feed

### ISSUE THREAD

**Issue by alinnert** [wasm-news/wasm.news#3]
I hope it's okay to open an issue like this in this repository.

I'm using the wasm.news RSS feed. Recently the article "Why WebAssembly is Faster Than asm.js" has been published. When I open the article from my RSS reader I see the following page:
https://wasm.news/2017/03/Why-WebAssembly-Is-Faster-Than-Asm.js

But there's no way to reach the actual article on hacks.mozilla.com. At least I can't see how I can get there. Can you please add a link to the actual article on the page I've linked above? That'd be great :)

**Comment by indus** [comment]
Sure thats ok. But I think I´ve done it correct - at least it works here: 
http://www.feedbucket.com/?src=https%3A%2F%2Fwasm.news%2Frss.xml
and here:
https://www.feed-reader.net/index.php?feedurl=https%3A%2F%2Fwasm.news%2Frss.xml&submit.x=18&submit.y=18

It is unclear to me what goes wrong in your feed-reader because the ```link``` tag is set correct.

**Comment by alinnert** [comment]
That's true... I'm using Feedly. Seems it's using the guid instead. I guess I need to ask them.

**Comment by indus** [comment]
With https://github.com/wasm-news/wasm.news/commit/cad4a987920ac35c14bd1ff93af544558fcf5320
I´ve made the title of the page a link to the ressource. So now  you can at least navigate forward to the external page. I hope this helps.

Grüße nach Straubing
